// Node >= 20; packaging only. Decompositions are generated by PARI/GP.
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {gzipSync} from 'node:zlib';
const root=path.resolve(import.meta.dirname,'..');
const registry=JSON.parse(await fs.readFile(path.join(root,'tools/sequences.json'),'utf8'));
// Optional IDs repack just those datasets while retaining the other manifests.
const selected=new Set(process.argv.slice(2));
for(const id of selected)if(!registry.some(s=>s.id===id))throw Error(`Unknown sequence: ${id}`);
const data=path.join(root,'dist/data');
const chunkSize=25000, pageSize=20;
registry.sort((a,b)=>Number(a.oeis.slice(1))-Number(b.oeis.slice(1)));
if(registry.length>100)throw Error("Atlas is closed at 100 sequences; no further decomposition additions.");
await fs.mkdir(path.join(data,'catalog'),{recursive:true});
const json=(f,v)=>fs.writeFile(f,JSON.stringify(v));
const digest=s=>crypto.createHash('sha256').update(s).digest('hex');
const search=[], catalog=[];
for(const seq of registry){
 if(!/^[a-z0-9-]+$/.test(seq.id))throw Error('Invalid id');
 if(selected.size&&!selected.has(seq.id)){
  const m=JSON.parse(await fs.readFile(path.join(data,seq.id,'manifest.json'),'utf8'));
  if(m.id!==seq.id||m.oeis!==seq.oeis||!Number.isSafeInteger(m.points)||m.points<1)throw Error('Invalid retained manifest');
  const page=Math.floor(catalog.length/pageSize);
  search.push([seq.id,seq.name,seq.oeis,page]);catalog.push({...seq,points:m.points,manifest:`../${seq.id}/manifest.json`});
  continue;
 }
 const raw=await fs.readFile(path.join(root,'raw',seq.id+'.csv'),'utf8');
 const lines=raw.trim().split(/\r?\n/); if(lines.shift()!=='n,a,k,L,d')throw Error('Bad header');
 const points=[], excluded=[]; const maxima=[1,1,1]; let weight=0,level=0,ties=0,previous;
 for(const line of lines){
  const cells=line.split(','); if(cells.length!==5||cells.some(x=>!/^\d+$/.test(x)))throw Error('Bad row');
  const b=cells.map(BigInt), [n,a,k,L,d]=b;
  if(b.some(x=>x>BigInt(Number.MAX_SAFE_INTEGER)))throw Error('Current viewer supports safe integers only');
  if(n<1n||a<0n||d<1n)throw Error('Invalid nonnegative term or positive index/gap');
  if(!previous && n!==BigInt(seq.indexOrigin??1))throw Error('Raw start index differs from metadata');
  if(previous && (a!==previous[1]+previous[4]||n!==previous[0]+1n))throw Error('Sequence discontinuity');
  previous=b;
  if(k===0n||L===0n){if(k!==0n||L!==0n||a>2n*d)throw Error('Invalid unclassified row');excluded.push(cells.map(Number));continue;}
  if(a<=2n*d||k<=d||k*L+d!==a)throw Error('Invalid WLJ identity');
  if(k>L)level++;else weight++;if(k===L)ties++;
  [Number(k),Number(L),Number(d)].forEach((x,i)=>maxima[i]=Math.max(maxima[i],x));points.push(line);
 }
 if(!points.length)throw Error('Empty sequence');
 const dir=path.join(data,seq.id);await fs.mkdir(dir,{recursive:true});
 const chunks=[];
 for(let start=0;start<points.length;start+=chunkSize){
  const rows=points.slice(start,start+chunkSize), text='n,a,k,L,d\n'+rows.join('\n')+'\n';
  const hash=digest(text),filename=`chunk-${String(chunks.length).padStart(4,'0')}-${hash.slice(0,12)}.csv.gz`;
  const compressed=gzipSync(text,{level:9});
  await fs.writeFile(path.join(dir,filename),compressed);
  chunks.push({file:filename,points:rows.length,bytes:Buffer.byteLength(text),sha256:hash,encoding:'gzip',compressedBytes:compressed.length});
 }
 const manifest={schema:1,...seq,points:points.length,terms:lines.length,excluded,classification:{weight,level,ties},maxima,chunkSize,chunks,coordinates:'ln(k),ln(L),ln(d)',integerEncoding:'safe-integer',indexOrigin:seq.indexOrigin??1};
 await json(path.join(dir,'manifest.json'),manifest);
 const page=Math.floor(catalog.length/pageSize);
 search.push([seq.id,seq.name,seq.oeis,page]);catalog.push({...seq,points:points.length,manifest:`../${seq.id}/manifest.json`});
 console.log(seq.id,points.length,'points',chunks.length,'chunks',excluded.length,'excluded');
}
for(let i=0;i<catalog.length;i+=pageSize)await json(path.join(data,'catalog',`page-${Math.floor(i/pageSize)}.json`),catalog.slice(i,i+pageSize));
await json(path.join(data,'catalog/search.json'),search);
await json(path.join(data,'catalog/index.json'),{schema:1,total:catalog.length,pageSize,search:'search.json',defaultSequence:'primes'});
